apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes: #  ReadWriteOnce, ReadOnlyMany -> Multiple nodes can read from this at the same time, ReadWriteMany
    - ReadWriteOnce # Can be used by a single node at the same time
  resources:
    requests:
      storage: 2Gi