apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP # Other Cluster can connect but not from the outside unlike NodePort
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
