apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP # Other Cluster can connect but not from the outside unlike NodePort
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
