apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP # Other Cluster can connect but not from the outside unlike NodePort
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000
